### PR TITLE
Align desktop view for home page

### PR DESCRIPTION
**Pull request by tantovanwijhe**
Team, 

I've adjusted some HTML/CSS to have the home page look aligned in desktop view:
- Banner background covers the screen width
- Footer text is centered 
- Removed left padding from bottom menubar (icons are now centered)

Let me know if you have any comments or questions to ask!
See images below for before/after:

### Banner
Screenshot 2022-09-19 at 12 09 45 PM
Screenshot 2022-09-19 at 12 09 40 PM

### Footer:
Screenshot 2022-09-19 at 12 10 07 PM
Screenshot 2022-09-19 at 12 09 59 PM

### + I removed left padding from the bottom menubar:
Screenshot 2022-09-19 at 12 10 32 PM
Screenshot 2022-09-19 at 12 10 50 PM

### CODE REVIEW

**Comment by InesCayolla** [comment]
It seems great to me. I can work on further adjustments this afternoon if you are done for today, I will keep you in touch.

**Comment by tantovanwijhe** [comment]
Thanks @InesCayolla :) 
I plan to make small changes every day, just to keep practising. I encourage you and @Palangsurati to do the same!

If you're out of ideas to work on, things to fix can be found in Kitt (https://kitt.lewagon.com/products/9286)

**Comment by Palangsurati** [comment]
sorry for being late.
about a top services, isn't it look better in web to be just a normal without scroll?

**Comment by tantovanwijhe** [comment]
@Palangsurati that's an idea worth exploring. See if you can improve Top Services in desktop view!

**Pull request merged**
